apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xmas-ingress
  namespace: xmas-k9s
  annotations:     
    nginx.ingress.kubernetes.io/use-regex: "true"      
    cert-manager.io/cluster-issuer: selfsigned-issuer
  
spec:  
  ingressClassName: nginx
  tls: 
  - hosts:   
    - www.xmas-k9s.tech
    - auth.xmas-k9s.tech
    - bot.xmas-k9s.tech
    - profile.xmas-k9s.tech  
    secretName: xmas-tls
  rules:  
  - host: www.xmas-k9s.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fe-endpoint
            port:
              number: 80
  - host: auth.xmas-k9s.tech
    http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-endpoint
            port:
              number: 80
  - host: bot.xmas-k9s.tech
    http:
      paths:
      - path: /api/bot
        pathType: Prefix
        backend:
          service:
            name: bot-endpoint
            port:
              number: 80
  - host: profile.xmas-k9s.tech
    http:
      paths:
      - path: /api/profile
        pathType: Prefix
        backend:
          service:
            name: profile-endpoint
            port:
              number: 80