apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: xmas-k9s
spec:
   replicas: 1
   selector:
      matchLabels:
         app: fe-service
   template:
      metadata:   
         labels:
            app: fe-service
      spec:
         containers:
         -  name: fe-docker-container
            image: hondocker23/fe-svc-r:2025-11-15-1432
            ports:
            - containerPort: 80                      
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-xmas
                readOnly: true
              - name: config-volume
                mountPath: /etc/config-xmas
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: xmas-secret     
           - name: config-volume
             configMap:
               name: xmas-config
