apiVersion: v1
kind: Service
metadata:
   name: profile-endpoint
   namespace: xmas-k9s
spec:
   selector:
      app: profile-service
   ports:
   - port: 80
     targetPort: 2025     
   type: ClusterIP   